// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUyTPSh_QRFp9AcZR6tRwXt7MX51GGAAE',
    appId: '1:344183238958:web:4372c32cc3ab7ef3554abf',
    messagingSenderId: '344183238958',
    projectId: 'ai-personal-bot',
    authDomain: 'ai-personal-bot.firebaseapp.com',
    storageBucket: 'ai-personal-bot.firebasestorage.app',
    measurementId: 'G-BWPDN4JQ9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh5BuW1C8DR6-n8lp7PZ0Xy1v91Y8lqHM',
    appId: '1:344183238958:android:b3af6c9168b4aa54554abf',
    messagingSenderId: '344183238958',
    projectId: 'ai-personal-bot',
    storageBucket: 'ai-personal-bot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANshh7DDJgcUYMr2yDBItX70sZBNEp3xM',
    appId: '1:344183238958:ios:3ba940d6bb2c87cd554abf',
    messagingSenderId: '344183238958',
    projectId: 'ai-personal-bot',
    storageBucket: 'ai-personal-bot.firebasestorage.app',
    iosClientId: '344183238958-oa6gbo68pln6nk9317tfj06n8u9cb42g.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiTaskbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANshh7DDJgcUYMr2yDBItX70sZBNEp3xM',
    appId: '1:344183238958:ios:3ba940d6bb2c87cd554abf',
    messagingSenderId: '344183238958',
    projectId: 'ai-personal-bot',
    storageBucket: 'ai-personal-bot.firebasestorage.app',
    iosClientId: '344183238958-oa6gbo68pln6nk9317tfj06n8u9cb42g.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiTaskbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUyTPSh_QRFp9AcZR6tRwXt7MX51GGAAE',
    appId: '1:344183238958:web:8d29bf5f79f460ea554abf',
    messagingSenderId: '344183238958',
    projectId: 'ai-personal-bot',
    authDomain: 'ai-personal-bot.firebaseapp.com',
    storageBucket: 'ai-personal-bot.firebasestorage.app',
    measurementId: 'G-5GT43M4PDC',
  );
}
